out.println("<div class='layui-col-md4 layui-col-sm6'>");
out.println("<div class='layadmin-contact-box' >"); 
out.println("<div class='layui-col-md4 layui-col-sm6'>");
out.println("<a href='javascript:;'>");
out.println("<div class='layadmin-text-center'>");
out.println("<img src='../../layuiadmin/style/res/template/character.jpg'>");
out.println("<div class='layadmin-maillist-img layadmin-font-blod'>");演员</div>");
out.println("</div>");
out.println("</a>");
out.println("</div>");
out.println("<div class='layui-col-md8 layadmin-padding-left20 layui-col-sm6'>");
out.println("<a href='javascript:;'>");
out.println("<h3 class='layadmin-title'>");
out.println("<strong>胡歌</strong>");
out.println("</h3>");
out.println("<p class='layadmin-textimg'>");
out.println("<i class='layui-icon layui-icon-location'>");</i>");
out.println("上海");
out.println("</p>");
out.println("</a>");
out.println("<div class='layadmin-address'>");
out.println("<a href='javascript:;'>");
out.println("<strong>Hu Ge studio</strong>");
out.println("<br>");
out.println("E-mail:xxx@baidu.com");
out.println("<br>");
out.println("Weibo: https://weibo.com/hu_ge ");
out.println("<br>");
out.println("<addr title='phone'>");Tel:</addr>");
out.println("(123) 456-7890");
out.println(" </a>");
out.println(" </div>");
out.println("</div>");
out.println("</div>");
out.println("</div>");